### ISSUE TITLE
Exception trying to load duty schedule

### ISSUE THREAD

**Issue by AlessioMartorelli** [arachnys/cabot#461] opened 2017-03-14 21:24 UTC
Hi,
I've noticed that lately my rota doesn't get picked up properly from Google. I've tried lowering the celery time to 120 seconds so that I could troubleshoot the issue and started celery manually to see the logs.
I've found out that it raises the following exception:
```
[2017-03-14 21:19:44,878: ERROR/MainProcess] Task cabot.cabotapp.tasks.update_shifts[f846c243-d526-4304-80cb-a290a9156f27] raised unexpected: TypeError("can't compare offset-naive and offset-aware datetimes",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cabot/cabot/cabotapp/tasks.py", line 79, in update_shifts
    _update_shifts()
  File "/cabot/cabot/cabotapp/models.py", line 971, in update_shifts
    events = get_events()
  File "/cabot/cabot/cabotapp/calendar.py", line 61, in get_events
    events.extend(_recurring_component_to_events(component))
  File "/cabot/cabot/cabotapp/calendar.py", line 33, in _recurring_component_to_events
    start_times = recur_set.between(utcnow, later)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/rrule.py", line 222, in between
    if i >= before:
TypeError: can't compare offset-naive and offset-aware datetimes
```

Nothing should have changed on my side; does anyone have any advice to understand what's going on?

Thank you

**Comment by JeanFred** [comment] 2017-03-15 01:31
@AlessioMartorelli Have you upgraded Cabot recently? Which version are you running?

**Comment by AlessioMartorelli** [comment] 2017-03-15 09:40
I've not upgraded Cabot, not intentionally at least. I'm using the docker-compose file.
Not sure how to see the version I'm running.

**Comment by frankh** [comment] 2017-03-15 12:59
Hi @AlessioMartorelli ,you should be able to get the version by running

`docker-compose run --rm web pip show cabot`

**Comment by AlessioMartorelli** [comment] 2017-03-15 13:11
Thanks @frankh !

```
Name: cabot
Version: 0.0.1.dev0
Summary: Self-hosted, easily-deployable monitoring and alerts service - like a lightweight PagerDuty
Home-page: http://cabotapp.com
Author: Arachnys
Author-email: info@arachnys.com
License: MIT
Location: /cabot
Requires: Django, Markdown, .....
....
```

**Comment by frankh** [comment] 2017-03-15 13:20
I guess the problem is your ical response is not timezone aware..

Could you send an example of your .ics file? (with any sensitive information removed)

**Comment by frankh** [comment] 2017-03-15 13:31
@AlessioMartorelli I managed to reproduce this, working on a fix

**Comment by AlessioMartorelli** [comment] 2017-03-15 13:32
Thank you very much!

**Comment by frankh** [comment] 2017-03-16 10:31
Hi @AlessioMartorelli 

This is now fixed in 0.9.2

In order to upgrade you need to first update to 0.6.0 and migrate, and then update to 0.9.2 and migrate with --fake-initial (this is because of migration changes in django 1.7).

We also now have an official docker image and docker-compose: https://hub.docker.com/r/cabotapp/cabot/, https://github.com/cabotapp/docker-cabot

**Closed by frankh** 2017-03-16 10:31 UTC

**Comment by AlessioMartorelli** [comment] 2017-03-16 16:56
Thanks a lot @frankh 
I'm already using cabot-docker. I've logged in to the app container and ran:

```
pip install --no-cache-dir --disable-pip-version-check cabot==0.6.0
root@fb4d2bda0aea:/cabot# python manage.py migrate                                                   
Running migrations for djcelery:
- Nothing to migrate.
 - Loading initial data for djcelery.
Installed 0 object(s) from 0 fixture(s)
Running migrations for cabotapp:
- Nothing to migrate.
 - Loading initial data for cabotapp.
Installed 0 object(s) from 0 fixture(s)
```
Am I doing the right thing or there's a better way?

**Comment by frankh** [comment] 2017-03-20 09:45
That looks right, i guess your migrations were already up to date so you just need to update to 0.9.2 now
