### ISSUE TITLE
No url file available for plugin cabot_alert_*

### ISSUE THREAD

**Issue by squareatom** [arachnys/cabot#186] opened 2015-02-12 20:01 UTC
Receiving these errors. Can someone point me in the right direction.

    ERROR 2015-02-12 19:52:45,910 urls 8002 140634817193920 No url file available for plugin cabot_alert_hipchat
    ERROR 2015-02-12 19:52:45,911 urls 8002 140634817193920 No url file available for plugin cabot_alert_email

**Comment by packetcollision** [comment] 2015-02-12 20:29
Can you provide a little more info about how you're invoking Cabot to get that error?

**Comment by bonniejools** [comment] 2015-02-12 20:55
@squareatom no URL file is supplied for either of those plugins however it should not be causing errors. Are these errors stopping you running cabot?

**Comment by squareatom** [comment] 2015-02-12 22:50
@packetcollision I managed to get cabot installed on a RHEL 6.5 (Python 2.6.x) local VM. I was able to do so mainly using https://gist.github.com/Gromph/5f4db73b0f38775bc2f0. So I've more than likely broken some things. Anything specific you'd like me to provide?

@bonniejools I can run cabot and it looks like everything need works except for sending emails. So I thought that might be the cause. Correct me if I'm wrong.

**Comment by bonniejools** [comment] 2015-02-12 23:32
No this won't be the cause. We've switched to a plugin system in the last couple of days and there may be a couple of bugs laying around. The [cabot-alert-email](https://www.github.com/bonniejools/cabot-alert-email.git) plugin may be causing problems so I'll take a look and see what I can find. I'll update you if I find any problems in the plugin.

**Comment by bonniejools** [comment] 2015-02-13 14:52
[I've fixed the bug](https://github.com/bonniejools/cabot-alert-email/commit/13fb1069af3e7242a2bf566d8d707f8785609d26) which is causing your problems. Thankyou very much for pointing this out. It's been fixed. Either update your plugins on the server or redeploy a new instance. It should be working now.

**Comment by squareatom** [comment] 2015-02-13 18:27
Thanks prob something on my end but..

Still doesn't seem to work. Also it doesn't look like the checks are being run automatically. When I hit the refresh button, however I see that they run.

**Comment by bonniejools** [comment] 2015-02-13 19:06
@squareatom Good that emails are working now. I'll see if I can fix that bug. As I've said before, there is no URL file for the email plugin however this shouldn't cause an error to be raised. I'll see what I can do.

**Comment by squareatom** [comment] 2015-02-13 19:23
@bonniejools The only emails I'm getting are the "ERROR: No url file..." ones. I'm not actually getting any for the alerts themselves. And what is this URL file? Thanks again for looking into this.

**Comment by jghward** [comment] 2015-02-21 17:57
@bonniejools I have the same issue here, no alert emails but am receiving the "ERROR: No url file.."

/var/log/cabot/celery-1.log contains the following: 

```
[2015-02-21 17:50:34,248: ERROR/Worker-11] Could not sent Email alert
Traceback (most recent call last):
  File "/home/ubuntu/2015-02-21-8362690/cabot/cabotapp/alert.py", line 50, in send_alert
    alert.send_alert(service, users, duty_officers)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/cabot_alert_email/models.py", line 29, in send_alert
    emails = [u.user.email for u in users]
AttributeError: 'User' object has no attribute 'user'
```

Thanks for your time.

**Comment by dbuxton** [comment] 2015-02-22 10:18
@jghward looks like https://github.com/bonniejools/cabot-alert-email/commit/12d8ad9c5f37c82e452b6f602ddb9f4f36d5e86a broke it - @bonniejools can you fix please?

**Comment by AvihayTsayeg** [comment] 2015-03-01 09:55
Hi,
Is there a solution here ?
I'm having the same issue, no email alerts are being sent.

**Comment by dbuxton** [comment] 2015-03-01 18:57
@bonniejools is this fixed yet?

It's possible to specify the plugin versions in the production.env file in normal requirements syntax but not sure if this is fixed upstream.

**Comment by bonniejools** [comment] 2015-03-01 23:35
@dbuxton Yes this has been fixed in cabot-alert-email 1.3.1.

The 'No URL available' error has been fixed in #191 which also sets a plugin version in the default production.env.

**Comment by bonniejools** [comment] 2015-03-01 23:36
@dbuxton should have mentioned it here but it slipped my mind.

**Comment by squareatom** [comment] 2015-03-10 21:49
As as update, I'm finally receiving the alert emails after doing a compete reinstall. So there was some issue with my install. The fix for No URL file will most likely work as I manually edited urls.py and did something similar to what's in your commit. Thanks for fixing this though. Next I think i will play around with the email template or work on my own plugin.

**Closed** 2015-03-10 21:49 UTC
