### ISSUE TITLE
does cabot have global alert switch off ?

### ISSUE THREAD

**Issue by rmrf** [arachnys/cabot#399] opened 2016-12-09 02:37 UTC
which is like in "maintainace mode", all of the alert generated will not send out. just display on portal page. 
the switch can turn on manually after maintainace finished.

**Comment by frankh** [comment] 2017-04-21 10:00
Duplicate of https://github.com/arachnys/cabot/issues/447

**Closed by frankh** 2017-04-21 10:00 UTC
Labels: duplicate
