### ISSUE TITLE
Is it possible to install Cabot without tugboat/fabric ?

### ISSUE THREAD

**Issue by hostingwalk** [arachnys/cabot#370] opened 2016-08-31 12:09 UTC
Hello,

I want to install Cabot but just local so without use of tugboat/fabric, but there is not documentation for that, can someone explain ?

**Comment by JeanFred** [comment] 2016-08-31 12:29
The `bin/provision` script should be doing that fine. It is used in the Vagrantfile.

**Comment by hostingwalk** [comment] 2016-08-31 12:48
`/cabot/bin# ./setup_dependencies.sh`    i have run this, or do i need to do more ?  
I see not a  502 Bad Gateway from Nginx

**Comment by dbuxton** [comment] 2016-09-02 10:58
Yes, `./provision`ing is separate from dependencies

**Comment by dbuxton** [comment] 2016-09-02 10:58
Closing this as not a bug

**Closed by dbuxton** 2016-09-02 10:58 UTC

**Comment by hostingwalk** [comment] 2016-09-02 11:31
How can i run  ./provision ?

**Comment by dbuxton** [comment] 2016-09-02 11:42
By typing `./provision`?

I think it would be worth you looking at the Fabric deployment script to see what it does: https://github.com/arachnys/cabot/blob/b72864ea8252dbb1739e33580fae04c26da4e44a/fabfile.py#L128

**Comment by hostingwalk** [comment] 2016-09-06 08:36
root@my:~/cabot/bin# ls
activate  activate.fish  provision  setup_dependencies.sh
root@my:~/cabot/bin# ./provision
./provision: line 5: cd: /vagrant: No such file or directory

**Comment by dbuxton** [comment] 2016-09-06 09:36
I'm afraid that we can't support this - this is what I would consider "basic" linux knowledge. `./provision` is specific to the vagrant environment (hence looking for a directory called `/vagrant`) but if you look at it you'll see that it does more-or-less general provisioning stuff.

Hope that helps.
